# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba211a82389da458530b60dbec18a2bf1233389e12688d7aa84f814d27d47485039f065267059f68ddecb56ca3b94372fb6303f46670fa7bf0b6f1d21fcafe66

test:
  secret_key_base: f69a31e099288bc126804e77effb3b61b246dca000b3b00999a56bf8ba5957dbc55783f2aea46c35e62e0ff8b79522ba09a633f31f50cf90578fd568c4b1898e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
